/**
 * The contract types a tracker UI works with, re-exported for hosts.
 *
 * Types only: nothing here survives compilation, so importing this file never pulls the zod schemas
 * (or the server contract) into a browser bundle. Anything that needs the schemas at runtime should
 * import `@kernhq/module-tracker/contract` instead.
 */

export type {
  ApprovalState,
  Attachment,
  AvailableTransition,
  BoardColumn,
  Comment,
  Component,
  CreateIssue,
  Cycle,
  CycleStatus,
  DateOnly,
  EstimateUnit,
  FieldDef,
  FieldLayoutItem,
  FieldOption,
  FieldType,
  GroupBy,
  IntakeForm,
  IntakeSubmission,
  Issue,
  IssueApproval,
  IssueHistoryEntry,
  IssueKey,
  IssueQueryInput,
  IssueQueryResult,
  IssueSummary,
  KqlFieldInfo,
  KqlParseResult,
  KqlSuggestion,
  Label,
  Link,
  Milestone,
  OrderBy,
  Priority,
  Project,
  ProjectKey,
  ProjectMember,
  ProjectTemplate,
  ProjectTemplateBody,
  ProjectTemplateId,
  ReactionSummary,
  RelationSummary,
  RelationType,
  RelationView,
  ResolvedField,
  ResolvedLayout,
  RichDoc,
  StatusCategory,
  StatusHistoryEntry,
  StatusInfo,
  SystemFieldId,
  Timer,
  TimesheetRow,
  UpdateIssue,
  Version,
  View,
  ViewDisplay,
  ViewLayout,
  Workflow,
  WorkItemType,
  Worklog,
} from '../contract/index.js'
